name: build_docker

on:
  push:
    branches:
    - main
    workflow_dispatch:  # Allows manual triggering

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download STM32CubeCLT release asset
        run: |
          curl -L \
            -o st-stm32cubeclt.zip \
            https://github.com/ftobler/docker-STM32CubeCLT/releases/download/test/st-stm32cubeclt_1.20.0_26822_20251117_1245_amd64.deb_bundle.sh.zip

      - name: Verify download
        # file after unzip is st-stm32cubeclt_1.20.0_26822_20251117_1245_amd64.deb_bundle.sh
        run: |
          unzip st-stm32cubeclt.zip
          ls
          mv st-stm32cubeclt_1.20.0_26822_20251117_1245_amd64.deb_bundle.sh st-stm32cubeclt_amd64.deb_bundle.sh
          ls

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          pull: false
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/STM32CubeCLT:latest