name: build_docker

on:
  push:
    branches:
    - main
    workflow_dispatch:  # Allows manual triggering

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download STM32CubeCLT release asset
        run: |
          curl -L \
            -o st-stm32cubeclt.zip \
            https://github.com/ftobler/docker-STM32CubeCLT/releases/download/st-stm32cubeclt_1.20.0_26822_20251117_1245_amd64.deb_bundle.sh/st-stm32cubeclt_1.20.0_26822_20251117_1245_amd64.deb_bundle.sh.zip

      - name: Verify download
        run: |
          ls -lh st-stm32cubeclt.zip
          unzip -l st-stm32cubeclt.zip